## Пример формирования решения в корректном формате

Чтобы система Яндекс.Контест смогла оценить точность прогноза вашей модели, требуется оформить посылку в определённом формате. Этот ноутбук демонстрирует процесс формирования таблицы с прогнозами простейшей модели для РТО магазинов на ноябрь 2024 года в корректном формате. Полученную табличку можно послать в систему, и прогнозы модели получат оценку. Используйте этот ноутбук как пример того, как должны выглядеть данные, посылаемые в Контест.

In [1]:
# импортируем библиотеку для работы с табличными данными
import pandas as pd

In [2]:
# загрузим имеющиеся у нас данные
# Внимание: чтобы эта ячейка отработала, файл train.csv должен находиться в той же директории, что и этот ноутбук
train = pd.read_csv('train.csv')

In [3]:
train.head()

,new_id,Месяц,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м),Количество касс,Флаг алкогольной лицензии,РТО
0,0,1,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,22041969.33
1,0,2,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23268490.57
2,0,3,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,24487732.21
3,0,4,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,23981980.29
4,0,5,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,9588,501,79,156,0,6,0,0,2,0,10,1,26608343.78

In [4]:
# Данные по какой месяц у нас в наличии?
train['Месяц'].max()

10

Видим, что у нас есть данные с января по октябрь. Нам требуется спрогнозировать РТО магазинов в ноябре.

При решении задач машинного обучения принято на первом шаге строить какое-нибудь максимально простое, даже наивное решение, чтобы последующие более сложные подходы сравнивать с ним и понимать, насколько мы смогли улучшить результат. Такое решение называется baseline-решением.

В задачах прогнозирования будущего популярным бейзлайн является использование в качестве предсказания последнее доступное значение в исторических данных. Например, прогнозируя, какая погода будет завтра, мы в качестве прогноза взяли бы сегодняшнюю температуру. Да, это неидеальная модель, и мы часто будем ошибаться, но в то же время нередко наш прогноз будет недалёк от истины. Кроме того, это очень простая модель, что хорошо для бейзлайн-решения.

Так и здесь: давайте попробуем в качестве предсказаний РТО в ноябре воспользоваться прогнозами октября. Мы пойдём даже на более сильное упрощение: возьмём прогнозы за октябрь, и усредним их по всем магазинам. Полученное значение будем использовать в качестве прогноза РТО за ноябрь. 

Это не самая качественная, но очень простая модель. Она и будет нашим бейзлайном. Помним, что целью этого ноутбука является не поиск идеального решения, а демонстрация того, как сформировать корректную посылку для нашей задачи в Яндекс.Контесте. Для наших целей такой простой прогноз более чем подходит. Чтобы задачу посчитали решённой, вам понадобиться набрать больше баллов, чем вы получити за это решение, но зато у вас будет пример корректной посылки.

Чтобы получить больше баллов, потребуется приложить больше усилий. Некоторым преимуществом нашего бейзлайна является то, что он очень примитивный, а значит, его легко преодолеть. Можно взять для каждого магазина своё последнее значение РТО. Можно построить более замысловатые модели из демонстрационного ноутбука. А можно попробовать придумать что-нибудь своё.

In [5]:
# Найдём средний РТО в октябре
train_oct = train[train['Месяц'] == train['Месяц'].max()]
avg_rto_oct = train_oct['РТО'].mean()

In [6]:
avg_rto_oct

np.float64(33503980.259272862)

In [7]:
# Сформируем список идентификаторов всех магазинов
shops_list = train['new_id'].unique()
print('Число магазинов:', len(shops_list))

Число магазинов: 20615

In [8]:
# Создадим объект DataFrame (аналог таблицы)
sample_submission = pd.DataFrame()
# Добавим столбец 'new_id' с идентификаторами магазинов
sample_submission['new_id'] = shops_list
# Добавим столбец 'rto', куда поместим значение нашего прогноза
sample_submission['rto'] = avg_rto_oct

In [9]:
# Вот так выглядит итоговая таблица
sample_submission

       new_id           rto
0           0  3.350398e+07
1           1  3.350398e+07
2           2  3.350398e+07
3           3  3.350398e+07
4           4  3.350398e+07
...       ...           ...
20610   21414  3.350398e+07
20611   21419  3.350398e+07
20612   21421  3.350398e+07
20613   21427  3.350398e+07
20614   21430  3.350398e+07

[20615 rows x 2 columns]

Сохраним таблицу с прогнозами в требуемом формате. Готово! Можно посылать решение в Контест.

Ожидаемый вердикт: OK

Ожидаемое число полученных баллов: 0

In [10]:
sample_submission.to_csv('test.csv', index=None)

Теперь в директории, где размещён ноутбук, появился файлик `test.csv`, который можно загружать в Контест!